services:
  oracle:
    container_name: oracle-sql-uread
    image: oracle
    environment:
      ORACLE_USER: uread
      ORACLE_PASS: 2024
      PGDATA: /var/lib/oracle/data
      ORACLE_DB: uread
    volumes:
      - oracle:/data/oracle
    ports:
      - 1521:1521
    networks:
      spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-uread
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  oracle:
    driver: local

    # docker-compose run up -d